import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider , SignIn } from '@clerk/nextjs'
import { SignedIn } from '@clerk/nextjs/app-beta'
import { SignedOut } from '@clerk/nextjs/app-beta/client'
import Navbar from '@/components/NavBar'
import { Outfit } from 'next/font/google'


// from here you can change the font
// const inter = Inter({ subsets: ['latin'] })
const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <SignedIn>
        <Navbar/>
        {children}
        </SignedIn>
        <SignedOut>
          <SignIn/>
        </SignedOut>
        </body>
    </html>
    </ClerkProvider>
  )
}
